### ISSUE TITLE
Update WebWrite InlineGUI for Backbone

### ISSUE THREAD

**Issue by balupton** [balupton/todo#15]
This is a continuation of #13

Progress started on this days ago on the dev branch:
https://github.com/webwrite/inlinegui/tree/dev

**Comment by pflannery** [comment]
Did you ever research [rendr](https://github.com/airbnb/rendr) ? would be nice to hear your thoughts if so.
It's an mvc shared client-server architecture based on Backbone. Seems real promising

**Comment by balupton** [comment]
Implemented.
