### ISSUE TITLE
Vegan movie night

### ISSUE THREAD

**Issue by balupton** [balupton/todo#20]
- Food matters: how what we eat can be good or bad
- Forks over Knives: health concerns with animal products (based on The China Study)
- Earthlings: where animals products come from

@robloach @patcon are you two down for this Tuesday night? Seb has said yes.

@yrassoulli would you also like to do this?

**Comment by yoshitamagoshi** [comment]
Will likely be at the office. I've seen all of those I believe.

**Comment by patcon** [comment]
My vote is for... Earthlings? :)

cc: @neilbaylorrulez

**Comment by RobLoach** [comment]
In.

**Comment by balupton** [comment]
Okay, sweet. We'll do earthlings first.

**Comment by greduan** [comment]
I imagine Earthlings will be gruesome. Good luck guys. lol. I'm glad I don't need convincing to be vegan, cause I don't plan to be. lol

**Comment by balupton** [comment]
@Greduan hrmm, I thought someone as responsible as you would definitely feel the inclination to be responsibly informed by learning what people pay people to do to animals on your behalf, the consequences to our only home (the planet), and the consequences to our health... "Earthlings will be gruesome" if it is gruesome, then it is only because that is what non-vegans do to animals... I'd prefer to live in a world, where I don't do anything gruesome to anyone (by me doing it directly, or by me doing it indirectly by ordering others to do so on my behalf).

**Comment by greduan** [comment]
> I'd prefer to live in a world, where I don't do anything gruesome to anyone (by me doing it directly, or by me doing it indirectly by ordering others to do so on my behalf).

Agreed. And that's why you have your own food instead of buying it, because eating animals can be not gruesome. In fact IMO it can be even artistic in a way.
